# Generated by Django 3.2.9 on 2021-11-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ingredients',
            field=models.ManyToManyField(related_name='product_ingredient', to='products.Ingredients'),
        ),
        migrations.DeleteModel(
            name='Product_ingredient',
        ),
    ]
