# Generated by Django 3.2.9 on 2021-11-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_images_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='menu_id',
            new_name='menu',
        ),
    ]
