# Generated by Django 3.2.9 on 2021-11-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211112_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredient',
            field=models.ManyToManyField(to='products.Ingredient'),
        ),
    ]
